Repository dukcode/sidedish, pull requests merged in 2022-04, with the labels that each got.

#1 [공통] PR 및 Issue 템플릿 추가
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📄documentation

#25 Init xcodproj
  .gitignore
  SideDishProject/.swiftlint.yml
  SideDishProject/Podfile
  SideDishProject/SideDishProject.xcodeproj/project.pbxproj
  SideDishProject/SideDishProject.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  SideDishProject/SideDishProject.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  SideDishProject/SideDishProject/AppDelegate.swift
  SideDishProject/SideDishProject/Assets.xcassets/AccentColor.colorset/Contents.json
  SideDishProject/SideDishProject/Assets.xcassets/AppIcon.appiconset/Contents.json
  SideDishProject/SideDishProject/Assets.xcassets/Contents.json
  SideDishProject/SideDishProject/Base.lproj/LaunchScreen.storyboard
  SideDishProject/SideDishProject/HomeViewController.swift
  SideDishProject/SideDishProject/Info.plist
  SideDishProject/SideDishProject/RootNavigationController.swift
  SideDishProject/SideDishProject/SceneDelegate.swift
  SideDishProject/SideDishProjectTests/SideDishProjectTests.swift
  SideDishProject/SideDishProjectUITests/SideDishProjectUITests.swift
  SideDishProject/SideDishProjectUITests/SideDishProjectUITestsLaunchTests.swift
Labels: 🍎 iOS

#32 feat - product를 생성하는 팩토리 구현 #24
  SideDishProject/SideDishProject.xcodeproj/project.pbxproj
  SideDishProject/SideDishProject/Product.swift
  SideDishProject/SideDishProject/ProductFactory.swift
Labels: 🍎 iOS

#39 [Feat] Repository 와 팩토리 연결
  SideDishProject/SideDishProject.xcodeproj/project.pbxproj
  SideDishProject/SideDishProject/HomeViewController.swift
  SideDishProject/SideDishProject/Product.swift
  SideDishProject/SideDishProject/ProductFactory.swift
  SideDishProject/SideDishProject/ProductRepository.swift
  SideDishProject/SideDishProject/SceneDelegate.swift
Labels: ✨ feature, 🍎 iOS

#41 feat - HomeView 생성 및 HomeViewController.view와 연결, NavigationControlle…
  SideDishProject/SideDishProject.xcodeproj/project.pbxproj
  SideDishProject/SideDishProject/AppDelegate.swift
  SideDishProject/SideDishProject/HomeView.swift
  SideDishProject/SideDishProject/HomeViewController.swift
  SideDishProject/SideDishProject/RootNavigationController.swift
Labels: 🍎 iOS

#50 feat - ViewController의존성 주입 #49
  SideDishProject/SideDishProject.xcodeproj/project.pbxproj
  SideDishProject/SideDishProject/DetailViewController.swift
  SideDishProject/SideDishProject/HomeViewController.swift
  SideDishProject/SideDishProject/SceneDelegate.swift
Labels: 🍎 iOS

#51 build - 스프링 부트 추가 프로젝트 설정
  BE/src/main/resources/application.properties
  BE/src/main/resources/application.yml
  BE/src/main/resources/logback-spring.xml
Labels: ⚙️ BE, ⚒️ build

#52 refactor - 오타수정
  SideDishProject/SideDishProject/HomeViewController.swift
Labels: 🍎 iOS

#53 feat: 전역 예외 처리 기능 추가
  BE/src/main/java/com/team25/sidedish/exception/ErrorResponse.java
  BE/src/main/java/com/team25/sidedish/exception/GlobalExceptionHandler.java
  BE/src/main/java/com/team25/sidedish/exception/GlobalRuntimeException.java
Labels: ⚙️ BE, ✨ feature

#58 feat: Entity 구현
  BE/src/main/java/com/team25/sidedish/domain/Category.java
  BE/src/main/java/com/team25/sidedish/domain/Delivery.java
  BE/src/main/java/com/team25/sidedish/domain/DeliveryType.java
  BE/src/main/java/com/team25/sidedish/domain/Event.java
  BE/src/main/java/com/team25/sidedish/domain/Image.java
  BE/src/main/java/com/team25/sidedish/domain/Product.java
  BE/src/main/java/com/team25/sidedish/domain/ProductDelivery.java
  BE/src/main/java/com/team25/sidedish/domain/ProductEvent.java
Labels: ⚙️ BE, ✨ feature

#63 1차 PR 코멘트 반영
  BE/HELP.md
  BE/src/main/java/com/team25/sidedish/exception/ErrorResponse.java
  BE/src/main/java/com/team25/sidedish/exception/GlobalExceptionHandler.java
  BE/src/main/java/com/team25/sidedish/exception/GlobalRuntimeException.java
  BE/src/main/java/com/team25/sidedish/exception/NotFoundException.java
Labels: ⚙️ BE

#65 test: Repository 레이어 테스트 코드 작성 (Category, Product, ProductEvent)
  BE/src/test/java/com/team25/sidedish/repository/CategoryRepositoryTest.java
  BE/src/test/java/com/team25/sidedish/repository/ProductEventRepositoryTest.java
  BE/src/test/java/com/team25/sidedish/repository/ProductRepositoryTest.java
Labels: ⚙️ BE, ✔️ test

#68 feat: Repository 구현 (Image, ProductDelivery)
  BE/src/main/java/com/team25/sidedish/domain/Delivery.java
  BE/src/main/java/com/team25/sidedish/domain/Image.java
  BE/src/main/java/com/team25/sidedish/repository/ImageRepository.java
  BE/src/main/java/com/team25/sidedish/repository/ProductDeliveryRepository.java
Labels: ⚙️ BE, ✨ feature

#69 test: Repository 레이어 테스트 코드 작성 (ProductDelivery, Image)
  BE/src/test/java/com/team25/sidedish/repository/ImageRepositoryTest.java
  BE/src/test/java/com/team25/sidedish/repository/ProductDeliveryRepositoryTest.java
Labels: ⚙️ BE, ✔️ test

#80 refactor: CategoryRepository 수정
  BE/src/main/java/com/team25/sidedish/repository/CategoryRepository.java
  BE/src/test/java/com/team25/sidedish/repository/CategoryRepositoryTest.java
Labels: ⚙️ BE, ♻️ refactor

#84 feat: Product 도메인, 레포지토리 기능 추가 및 테스트 코드 작성
  BE/src/main/java/com/team25/sidedish/domain/Product.java
  BE/src/main/java/com/team25/sidedish/exception/NotEnoughStockException.java
  BE/src/main/java/com/team25/sidedish/repository/ProductRepository.java
  BE/src/test/java/com/team25/sidedish/repository/ProductRepositoryTest.java
Labels: ⚙️ BE, ✨ feature

#89 feat: Service 레이어 구현
  BE/src/main/java/com/team25/sidedish/service/CategoryService.java
  BE/src/main/java/com/team25/sidedish/service/ImageService.java
  BE/src/main/java/com/team25/sidedish/service/ProductDeliveryService.java
  BE/src/main/java/com/team25/sidedish/service/ProductEventService.java
  BE/src/main/java/com/team25/sidedish/service/ProductService.java
Labels: ⚙️ BE, ✨ feature

#93 feat: Product Entity 속성 추가
  BE/src/main/java/com/team25/sidedish/domain/Product.java
  BE/src/main/java/com/team25/sidedish/repository/ProductRepository.java
  BE/src/main/resources/ddl.sql
  BE/src/main/resources/dml.sql
  BE/src/test/java/com/team25/sidedish/repository/ProductRepositoryTest.java
Labels: ⚙️ BE, ✨ feature

#96 feat: Product 도메인 기능 추가
  BE/src/main/java/com/team25/sidedish/domain/Product.java
Labels: ⚙️ BE, ✨ feature

#97 refactor: Delivery 도메인 수정
  BE/src/main/java/com/team25/sidedish/domain/Delivery.java
  BE/src/main/java/com/team25/sidedish/repository/ProductDeliveryRepository.java
  BE/src/main/resources/ddl.sql
  BE/src/main/resources/dml.sql
  BE/src/test/java/com/team25/sidedish/repository/ProductDeliveryRepositoryTest.java
Labels: ⚙️ BE, ♻️ refactor

#98 feat: DTO 구현
  BE/src/main/java/com/team25/sidedish/dto/request/ProductStockChangeRequest.java
  BE/src/main/java/com/team25/sidedish/dto/response/CategoryResponse.java
  BE/src/main/java/com/team25/sidedish/dto/response/ProductDetailResponse.java
  BE/src/main/java/com/team25/sidedish/dto/response/ProductResponse.java
  BE/src/main/java/com/team25/sidedish/dto/response/ProductStockChangeResponse.java
Labels: ⚙️ BE, ✨ feature

#99 feat: AggregateProductService 구현
  BE/src/main/java/com/team25/sidedish/service/aggregate/AggregateProductService.java
Labels: ⚙️ BE, ✨ feature

#100 feat: Category 레이어 구현
  BE/src/main/java/com/team25/sidedish/controller/CategoryController.java
  BE/src/main/java/com/team25/sidedish/controller/ProductController.java
Labels: ⚙️ BE, ✨ feature, EPIC

#115 feat: API 문서 자동화-1
  BE/build.gradle
  BE/src/main/java/com/team25/sidedish/config/SwaggerConfig.java
  BE/src/main/java/com/team25/sidedish/controller/ProductController.java
  BE/src/main/java/com/team25/sidedish/dto/request/ProductStockChangeRequest.java
  BE/src/main/java/com/team25/sidedish/dto/response/ProductResponse.java
  BE/src/main/java/com/team25/sidedish/dto/response/ProductStockChangeResponse.java
Labels: 📄 documentation, ⚙️ BE, ✨ feature

#117 refactor - 리뷰 수정 및 Cell의 오토레이아웃 충돌 해결 #101
  .DS_Store
  SideDishProject/.DS_Store
  SideDishProject/Podfile.lock
  SideDishProject/SideDishProject.xcodeproj/project.pbxproj
  SideDishProject/SideDishProject.xcworkspace/contents.xcworkspacedata
  SideDishProject/SideDishProject.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  SideDishProject/SideDishProject/DishCollectionViewCell.swift
  SideDishProject/SideDishProject/DishCollectionWrapper.swift
  SideDishProject/SideDishProject/HomeView.swift
  SideDishProject/SideDishProject/HomeViewController.swift
  SideDishProject/SideDishProject/MockDetailRepository.swift
  SideDishProject/SideDishProject/Product.swift
  SideDishProject/SideDishProject/ProductModel.swift
  SideDishProject/SideDishProject/ProductRepository.swift
  SideDishProject/SideDishProject/ProductSceneContainer.swift
  SideDishProject/SideDishProject/RootNavigationController.swift
Labels: 🍎 iOS

#118 Refactor 101
  .DS_Store
  SideDishProject/.DS_Store
  SideDishProject/Podfile.lock
Labels: 🍎 iOS

#116 feat: API 문서 자동화-2
  BE/src/main/java/com/team25/sidedish/controller/CategoryController.java
  BE/src/main/java/com/team25/sidedish/dto/response/CategoryResponse.java
  BE/src/main/java/com/team25/sidedish/dto/response/ProductDetailResponse.java
Labels: 📄 documentation, ⚙️ BE, ✨ feature

#126 refactor - 변수명 변경 및 토스터 오류 해결
  SideDishProject/Podfile
  SideDishProject/SideDishProject.xcodeproj/project.pbxproj
  SideDishProject/SideDishProject/DetailViewController.swift
  SideDishProject/SideDishProject/ProductSceneContainer.swift
Labels: 🍎 iOS

#127 feat: 개발환경 Profile 추가 및 mysql 연동
  BE/build.gradle
  BE/src/main/resources/application.yml
  BE/src/main/resources/logback-spring.xml
Labels: ⚙️ BE, ✨ feature

#129 fix: 테이블 이름 대문자 -> 소문자 수정
  BE/src/main/java/com/team25/sidedish/repository/ImageRepository.java
  BE/src/main/java/com/team25/sidedish/repository/ProductDeliveryRepository.java
  BE/src/main/java/com/team25/sidedish/repository/ProductEventRepository.java
  BE/src/main/java/com/team25/sidedish/repository/ProductRepository.java
  BE/src/main/resources/ddl.sql
  BE/src/main/resources/dml.sql
Labels: 🪲bugFix, ⚙️ BE

#131 Refactor 101
  SideDishProject/SideDishProject.xcodeproj/project.pbxproj
  SideDishProject/SideDishProject/applifecycle/AppDelegate.swift
  SideDishProject/SideDishProject/applifecycle/SceneDelegate.swift
  SideDishProject/SideDishProject/model/Product.swift
  SideDishProject/SideDishProject/repository/MockDetailRepository.swift
  SideDishProject/SideDishProject/repository/ProductRepository.swift
  SideDishProject/SideDishProject/usecase/DetailUsecase.swift
  SideDishProject/SideDishProject/usecase/HomeUsecase.swift
  SideDishProject/SideDishProject/usecase/MockProductFactory.swift
  SideDishProject/SideDishProject/usecase/ProductSceneContainer.swift
  SideDishProject/SideDishProject/view/DetailViewController.swift
  SideDishProject/SideDishProject/view/DishCollectionDataSource.swift
  SideDishProject/SideDishProject/view/DishCollectionDelegate.swift
  SideDishProject/SideDishProject/view/DishCollectionViewCell.swift
  SideDishProject/SideDishProject/view/DishCommetHeaderView.swift
  SideDishProject/SideDishProject/view/HomeView.swift
  SideDishProject/SideDishProject/view/HomeViewController.swift
Labels: 🍎 iOS

#132 refactor - 셀에 이벤트 버튼 겹쳐보이는 오류 수정 #40
  SideDishProject/SideDishProject/view/DishCollectionViewCell.swift
Labels: 🍎 iOS

#133 Feat 102
  BE/src/main/java/com/team25/sidedish/controller/ProductController.java
  BE/src/main/java/com/team25/sidedish/dto/request/ProductStockChangeRequest.java
  BE/src/main/java/com/team25/sidedish/dto/response/ErrorResponse.java
  BE/src/main/java/com/team25/sidedish/exception/CategoryNotExistException.java
  BE/src/main/java/com/team25/sidedish/exception/ExceptionController.java
  BE/src/main/java/com/team25/sidedish/exception/NotExistException.java
  BE/src/main/java/com/team25/sidedish/exception/NotFoundException.java
  BE/src/main/java/com/team25/sidedish/exception/ProductNotExistException.java
  BE/src/main/java/com/team25/sidedish/repository/ImageRepository.java
  BE/src/main/java/com/team25/sidedish/repository/ProductDeliveryRepository.java
  BE/src/main/java/com/team25/sidedish/repository/ProductEventRepository.java
  BE/src/main/java/com/team25/sidedish/repository/ProductRepository.java
  BE/src/main/java/com/team25/sidedish/service/CategoryService.java
  BE/src/main/java/com/team25/sidedish/service/ImageService.java
  BE/src/main/java/com/team25/sidedish/service/ProductDeliveryService.java
  BE/src/main/java/com/team25/sidedish/service/ProductEventService.java
  BE/src/main/java/com/team25/sidedish/service/ProductService.java
  BE/src/main/java/com/team25/sidedish/service/aggregate/AggregateProductService.java
  BE/src/test/java/com/team25/sidedish/repository/ImageRepositoryTest.java
Labels: ⚙️ BE, ✨ feature, EPIC

#134 docs: Swagger 어노테이션 수정
  BE/src/main/java/com/team25/sidedish/controller/ProductController.java
Labels: 📄 documentation, ⚙️ BE

#136 feat - 이미지 화면에 보여주기 기능 구현 - #135
  SideDishProject/SideDishProject/Info.plist
  SideDishProject/SideDishProject/model/Product.swift
  SideDishProject/SideDishProject/repository/ProductRepository.swift
  SideDishProject/SideDishProject/usecase/HomeUsecase.swift
  SideDishProject/SideDishProject/usecase/MockProductFactory.swift
  SideDishProject/SideDishProject/view/DishCollectionDataSource.swift
  SideDishProject/SideDishProject/view/DishCollectionViewCell.swift
  SideDishProject/SideDishProject/view/HomeView.swift
  SideDishProject/SideDishProject/view/HomeViewController.swift
Labels: 🍎 iOS

#138 refactor - 옵셔널바인딩 처리. #135
  SideDishProject/SideDishProject/repository/ProductRepository.swift
Labels: 🍎 iOS

#139 refactor - protocol 함수 인자값 변경 #135
  SideDishProject/SideDishProject/usecase/HomeUsecase.swift
Labels: 🍎 iOS

#142 refactor: (#141) Category 를 Struct 타입으로 변경
  SideDishProject/SideDishProject/model/Product.swift
  SideDishProject/SideDishProject/repository/ProductRepository.swift
  SideDishProject/SideDishProject/usecase/HomeUsecase.swift
  SideDishProject/SideDishProject/usecase/MockProductFactory.swift
  SideDishProject/SideDishProject/view/DishCollectionDataSource.swift
Labels: 🪲bugFix, 🍎 iOS, ♻️ refactor

#147 feat- 네트워크 fetchall 구현 완료 #144
  SideDishProject/Podfile
  SideDishProject/SideDishProject/applifecycle/SceneDelegate.swift
  SideDishProject/SideDishProject/models/DTO/ProductDTO.swift
  SideDishProject/SideDishProject/models/Entity/Product.swift
  SideDishProject/SideDishProject/repository/ProductNetworkRepository.swift
  SideDishProject/SideDishProject/repository/ProductRepository.swift
  SideDishProject/SideDishProject/service/ProductAPI.swift
  SideDishProject/SideDishProject/service/ProductService.swift
  SideDishProject/SideDishProject/view/HomeViewController.swift
Labels: 🍎 iOS
